### ISSUE TITLE
hello，爬虫代码可以学习一下么？

### ISSUE THREAD

**Issue by ghost** [South-River/CC98-mmpictures#2]
我搞了半天也没有爬成功，呜呜呜

**Comment by South-River** [comment]
代码就不贴了，萌新爬资源代码写的不多，也在学习中。
我用的是selenium库，因为没找到cookie用requests库不大方便（当然requests会快很多，但也有点问题，后面会说到）。
首先登录。
接着转到版面，获得版面的html，可以用正则表达式（例如'mm[\s\S]*(/topic/[0-9]{7})'）匹配包含“mm图片”、"/topic/***"的内容。这样你就获得了mm图片类别的主题帖的url。
然后再进入url，使用正则表达式读取图片的网址，例如'http[\s\S]*.jpg'。建议仅匹配一楼回复，因为后面的楼有些图片是表情包而不是小姐姐，可以通过这样的表达式匹配一楼回复'class="reply" id="1"([\s\S]*)class="reply" id="2"'。
然后你就得到图片的地址了，最后下载即可。但是98对图片采取了lazyload，即你的屏幕划到对应位置才会加载图片。所以建议加一个下滑到底的操作(这个操作貌似只有selenium有？因为它是模仿人去操作）。比如这样
```python
for l in range(1000):
    js='window.scrollBy(0,100)'
    driver.execute_script(js)
```
